import Head from "next/head";
import Navegacion from "./Navegacion";
import Footer from "./Footer";

const Layout = ({ children, page }) => {
  return (
    <div>
      <Head>
        <title>Kruger - {page}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navegacion />
      {children}
      <Footer />
    </div>
  );
};

export default Layout;
